// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexGxsKcKB_9Rzb3xqN07Lv9Uki2osvn0',
    appId: '1:127998770326:web:3132e97888b246a5bd96b7',
    messagingSenderId: '127998770326',
    projectId: 'dorak-eb4a4',
    authDomain: 'dorak-eb4a4.firebaseapp.com',
    storageBucket: 'dorak-eb4a4.firebasestorage.app',
    measurementId: 'G-3CRXYZ8P6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIuahBLBWZ9tBO96r8SetP1GYfbPWXQUM',
    appId: '1:127998770326:android:937b4be7fc3900bebd96b7',
    messagingSenderId: '127998770326',
    projectId: 'dorak-eb4a4',
    storageBucket: 'dorak-eb4a4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqL3e198-7Tz7vjnShudsVd5iiyA-JB-k',
    appId: '1:127998770326:ios:75c2a721f52f8d9bbd96b7',
    messagingSenderId: '127998770326',
    projectId: 'dorak-eb4a4',
    storageBucket: 'dorak-eb4a4.firebasestorage.app',
    iosBundleId: 'com.example.dorakApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqL3e198-7Tz7vjnShudsVd5iiyA-JB-k',
    appId: '1:127998770326:ios:75c2a721f52f8d9bbd96b7',
    messagingSenderId: '127998770326',
    projectId: 'dorak-eb4a4',
    storageBucket: 'dorak-eb4a4.firebasestorage.app',
    iosBundleId: 'com.example.dorakApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDexGxsKcKB_9Rzb3xqN07Lv9Uki2osvn0',
    appId: '1:127998770326:web:57b6474da3cc5066bd96b7',
    messagingSenderId: '127998770326',
    projectId: 'dorak-eb4a4',
    authDomain: 'dorak-eb4a4.firebaseapp.com',
    storageBucket: 'dorak-eb4a4.firebasestorage.app',
    measurementId: 'G-64YB88QR6G',
  );
}
